version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: true
  enable-build-vcs: true
  allow-parallel-runners: true
  allow-serial-runners: true

formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: strict
    warn-unused: true
    paths:
      - api
      - internal/platform/db/sqlc

linters:
  default: standard
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - revive
    - rowserrcheck
    - sqlclosecheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    govet:
      enable-all: true
    revive:
      severity: warning
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - api
      - internal/platform/db/sqlc
    rules:
      - path: _test\.go
        linters:
          - gosec
          - noctx
          - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: false

severity:
  default: error