version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true
  go: "1.26"

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - revgrep
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - PREALLOC
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagalign
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  cyclop:
    max-complexity: 15
  revive:
    rules:
      - name: blank-imports
      - name: context-as-first-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  lll:
    line-length: 120
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: internal/platform/db/sqlc/
      linters:
        - revive
        - stylecheck
        - lll

output:
  formats:
    - name: colored-line-number
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
