// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id, tenant_id, user_id, name, type, currency, balance_cents, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
) RETURNING id, tenant_id, user_id, name, type, currency, balance_cents, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	ID           string      `json:"id"`
	TenantID     string      `json:"tenant_id"`
	UserID       string      `json:"user_id"`
	Name         string      `json:"name"`
	Type         AccountType `json:"type"`
	Currency     string      `json:"currency"`
	BalanceCents int64       `json:"balance_cents"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.BalanceCents,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, tenant_id, user_id, name, type, currency, balance_cents, created_at, updated_at, deleted_at
FROM accounts
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetAccountByIDParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, arg.TenantID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByTenant = `-- name: ListAccountsByTenant :many
SELECT id, tenant_id, user_id, name, type, currency, balance_cents, created_at, updated_at, deleted_at
FROM accounts
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListAccountsByTenant(ctx context.Context, tenantID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.BalanceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, tenant_id, user_id, name, type, currency, balance_cents, created_at, updated_at, deleted_at
FROM accounts
WHERE tenant_id = $1 AND user_id = $2 AND deleted_at IS NULL
ORDER BY name ASC
`

type ListAccountsByUserParams struct {
	TenantID string `json:"tenant_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) ListAccountsByUser(ctx context.Context, arg ListAccountsByUserParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.BalanceCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE accounts
SET deleted_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteAccountParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error {
	_, err := q.db.Exec(ctx, softDeleteAccount, arg.TenantID, arg.ID)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $3,
    type = $4,
    currency = $5,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, user_id, name, type, currency, balance_cents, created_at, updated_at, deleted_at
`

type UpdateAccountParams struct {
	TenantID string      `json:"tenant_id"`
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Type     AccountType `json:"type"`
	Currency string      `json:"currency"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.BalanceCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance_cents = $3,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type UpdateAccountBalanceParams struct {
	TenantID     string `json:"tenant_id"`
	ID           string `json:"id"`
	BalanceCents int64  `json:"balance_cents"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.TenantID, arg.ID, arg.BalanceCents)
	return err
}
