// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_tenants.sql

package sqlc

import (
	"context"
)

const adminGetTenantByID = `-- name: AdminGetTenantByID :one
SELECT id, name, plan, created_at, updated_at, deleted_at
FROM tenants
WHERE id = $1
`

func (q *Queries) AdminGetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, adminGetTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const adminHardDeleteTenant = `-- name: AdminHardDeleteTenant :exec
DELETE FROM tenants
WHERE id = $1
`

func (q *Queries) AdminHardDeleteTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, adminHardDeleteTenant, id)
	return err
}

const adminListAllTenants = `-- name: AdminListAllTenants :many
SELECT id, name, plan, created_at, updated_at, deleted_at
FROM tenants
WHERE ($1::boolean = true OR deleted_at IS NULL)
ORDER BY name ASC
`

func (q *Queries) AdminListAllTenants(ctx context.Context, withDeleted bool) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, adminListAllTenants, withDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Plan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRestoreTenant = `-- name: AdminRestoreTenant :exec
UPDATE tenants
SET deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) AdminRestoreTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, adminRestoreTenant, id)
	return err
}

const adminSuspendTenant = `-- name: AdminSuspendTenant :exec
UPDATE tenants
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) AdminSuspendTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, adminSuspendTenant, id)
	return err
}

const adminUpdateTenantPlan = `-- name: AdminUpdateTenantPlan :one
UPDATE tenants
SET plan = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, plan, created_at, updated_at, deleted_at
`

type AdminUpdateTenantPlanParams struct {
	ID   string     `json:"id"`
	Plan TenantPlan `json:"plan"`
}

func (q *Queries) AdminUpdateTenantPlan(ctx context.Context, arg AdminUpdateTenantPlanParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, adminUpdateTenantPlan, arg.ID, arg.Plan)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
