// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListAllAuditLogs = `-- name: AdminListAllAuditLogs :many
SELECT id, tenant_id, actor_id, actor_role, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent, created_at
FROM audit_logs
WHERE (entity_type = $1 OR $1 IS NULL)
  AND (entity_id = $2 OR $2 IS NULL)
  AND (actor_id = $3 OR $3 = '')
  AND (action = $4 OR $4 IS NULL)
  AND (created_at >= $5 OR $5 IS NULL)
  AND (created_at <= $6 OR $6 IS NULL)
ORDER BY created_at DESC
LIMIT $8 OFFSET $7
`

type AdminListAllAuditLogsParams struct {
	EntityType pgtype.Text        `json:"entity_type"`
	EntityID   pgtype.Text        `json:"entity_id"`
	ActorID    string             `json:"actor_id"`
	Action     NullAuditAction    `json:"action"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
	OffsetOff  int32              `json:"offset_off"`
	LimitOff   int32              `json:"limit_off"`
}

func (q *Queries) AdminListAllAuditLogs(ctx context.Context, arg AdminListAllAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, adminListAllAuditLogs,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.Action,
		arg.StartDate,
		arg.EndDate,
		arg.OffsetOff,
		arg.LimitOff,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
