// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package sqlc

import (
	"context"
)

const adminForceDeleteUser = `-- name: AdminForceDeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) AdminForceDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, adminForceDeleteUser, id)
	return err
}

const adminGetUserByID = `-- name: AdminGetUserByID :one
SELECT id, tenant_id, email, name, role, last_login_at, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
`

func (q *Queries) AdminGetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, adminGetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const adminListAllUsers = `-- name: AdminListAllUsers :many
SELECT id, tenant_id, email, name, role, last_login_at, created_at, updated_at, deleted_at
FROM users
ORDER BY created_at ASC
`

func (q *Queries) AdminListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, adminListAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
