// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (id, ticker, isin, name, asset_type, currency, details, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
RETURNING id, ticker, isin, name, asset_type, currency, details, created_at
`

type CreateAssetParams struct {
	ID        string      `json:"id"`
	Ticker    string      `json:"ticker"`
	Isin      pgtype.Text `json:"isin"`
	Name      string      `json:"name"`
	AssetType AssetType   `json:"asset_type"`
	Currency  string      `json:"currency"`
	Details   pgtype.Text `json:"details"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.Ticker,
		arg.Isin,
		arg.Name,
		arg.AssetType,
		arg.Currency,
		arg.Details,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Isin,
		&i.Name,
		&i.AssetType,
		&i.Currency,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, ticker, isin, name, asset_type, currency, details, created_at FROM assets
WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Isin,
		&i.Name,
		&i.AssetType,
		&i.Currency,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetByTicker = `-- name: GetAssetByTicker :one
SELECT id, ticker, isin, name, asset_type, currency, details, created_at FROM assets
WHERE ticker = $1
`

func (q *Queries) GetAssetByTicker(ctx context.Context, ticker string) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByTicker, ticker)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Isin,
		&i.Name,
		&i.AssetType,
		&i.Currency,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, ticker, isin, name, asset_type, currency, details, created_at FROM assets
ORDER BY ticker ASC
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Isin,
			&i.Name,
			&i.AssetType,
			&i.Currency,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
