// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    id, tenant_id, actor_id, actor_role, action, 
    entity_type, entity_id, old_values, new_values, 
    ip_address, user_agent, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
) RETURNING id, tenant_id, actor_id, actor_role, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent, created_at
`

type CreateAuditLogParams struct {
	ID         string      `json:"id"`
	TenantID   string      `json:"tenant_id"`
	ActorID    string      `json:"actor_id"`
	ActorRole  UserRole    `json:"actor_role"`
	Action     AuditAction `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.Text `json:"entity_id"`
	OldValues  []byte      `json:"old_values"`
	NewValues  []byte      `json:"new_values"`
	IpAddress  *netip.Addr `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.ActorRole,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.OldValues,
		&i.NewValues,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, tenant_id, actor_id, actor_role, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent, created_at
FROM audit_logs
WHERE tenant_id = $1 AND entity_type = $2 AND entity_id = $3
ORDER BY created_at DESC
`

type ListAuditLogsByEntityParams struct {
	TenantID   string      `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.Text `json:"entity_id"`
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.TenantID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTenant = `-- name: ListAuditLogsByTenant :many
SELECT id, tenant_id, actor_id, actor_role, action, entity_type, entity_id, old_values, new_values, ip_address, user_agent, created_at
FROM audit_logs
WHERE (tenant_id = $1 OR tenant_id IS NULL) -- Allow global sysadmin logs
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAuditLogsByTenantParams struct {
	TenantID  string `json:"tenant_id"`
	OffsetOff int32  `json:"offset_off"`
	LimitOff  int32  `json:"limit_off"`
}

func (q *Queries) ListAuditLogsByTenant(ctx context.Context, arg ListAuditLogsByTenantParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByTenant, arg.TenantID, arg.OffsetOff, arg.LimitOff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValues,
			&i.NewValues,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
