// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTPRequest = `-- name: CreateOTPRequest :one
INSERT INTO otp_requests (
    id, email, code_hash, used, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
) RETURNING id, email, code_hash, used, expires_at, created_at
`

type CreateOTPRequestParams struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	Used      bool               `json:"used"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTPRequest(ctx context.Context, arg CreateOTPRequestParams) (OtpRequest, error) {
	row := q.db.QueryRow(ctx, createOTPRequest,
		arg.ID,
		arg.Email,
		arg.CodeHash,
		arg.Used,
		arg.ExpiresAt,
	)
	var i OtpRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM otp_requests
WHERE expires_at < NOW() OR (used = TRUE AND created_at < NOW() - INTERVAL '24 hours')
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const getActiveOTPByEmail = `-- name: GetActiveOTPByEmail :one
SELECT id, email, code_hash, used, expires_at, created_at
FROM otp_requests
WHERE email = $1 AND used = FALSE AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveOTPByEmail(ctx context.Context, email string) (OtpRequest, error) {
	row := q.db.QueryRow(ctx, getActiveOTPByEmail, email)
	var i OtpRequest
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE otp_requests
SET used = TRUE
WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}
