// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    id, tenant_id, parent_id, name, icon, color, type, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW(), NOW()
) RETURNING id, tenant_id, parent_id, name, icon, color, type, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	ID       string       `json:"id"`
	TenantID string       `json:"tenant_id"`
	ParentID string       `json:"parent_id"`
	Name     string       `json:"name"`
	Icon     pgtype.Text  `json:"icon"`
	Color    pgtype.Text  `json:"color"`
	Type     CategoryType `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.TenantID,
		arg.ParentID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, tenant_id, parent_id, name, icon, color, type, created_at, updated_at, deleted_at FROM categories
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetCategoryByIDParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.TenantID, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategoriesByTenant = `-- name: ListCategoriesByTenant :many
SELECT id, tenant_id, parent_id, name, icon, color, type, created_at, updated_at, deleted_at FROM categories
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListCategoriesByTenant(ctx context.Context, tenantID string) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCategories = `-- name: ListChildCategories :many
SELECT id, tenant_id, parent_id, name, icon, color, type, created_at, updated_at, deleted_at FROM categories
WHERE tenant_id = $1 AND parent_id = $2 AND deleted_at IS NULL
ORDER BY name ASC
`

type ListChildCategoriesParams struct {
	TenantID string `json:"tenant_id"`
	ParentID string `json:"parent_id"`
}

func (q *Queries) ListChildCategories(ctx context.Context, arg ListChildCategoriesParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listChildCategories, arg.TenantID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories
SET deleted_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

type SoftDeleteCategoryParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, arg.TenantID, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET 
    parent_id = $3,
    name = $4,
    icon = $5,
    color = $6,
    type = $7,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, parent_id, name, icon, color, type, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	TenantID string       `json:"tenant_id"`
	ID       string       `json:"id"`
	ParentID string       `json:"parent_id"`
	Name     string       `json:"name"`
	Icon     pgtype.Text  `json:"icon"`
	Color    pgtype.Text  `json:"color"`
	Type     CategoryType `json:"type"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.TenantID,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
