// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: master_purchases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMasterPurchase = `-- name: CreateMasterPurchase :one
INSERT INTO master_purchases (
    id,
    tenant_id,
    account_id,
    category_id,
    user_id,
    description,
    total_amount_cents,
    installment_count,
    closing_day,
    first_installment_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, tenant_id, account_id, category_id, user_id, description, status, total_amount_cents, installment_count, paid_installments, closing_day, first_installment_date, created_at, updated_at, deleted_at
`

type CreateMasterPurchaseParams struct {
	ID                   string      `json:"id"`
	TenantID             string      `json:"tenant_id"`
	AccountID            string      `json:"account_id"`
	CategoryID           string      `json:"category_id"`
	UserID               string      `json:"user_id"`
	Description          string      `json:"description"`
	TotalAmountCents     int64       `json:"total_amount_cents"`
	InstallmentCount     int16       `json:"installment_count"`
	ClosingDay           int16       `json:"closing_day"`
	FirstInstallmentDate pgtype.Date `json:"first_installment_date"`
}

func (q *Queries) CreateMasterPurchase(ctx context.Context, arg CreateMasterPurchaseParams) (MasterPurchase, error) {
	row := q.db.QueryRow(ctx, createMasterPurchase,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.CategoryID,
		arg.UserID,
		arg.Description,
		arg.TotalAmountCents,
		arg.InstallmentCount,
		arg.ClosingDay,
		arg.FirstInstallmentDate,
	)
	var i MasterPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CategoryID,
		&i.UserID,
		&i.Description,
		&i.Status,
		&i.TotalAmountCents,
		&i.InstallmentCount,
		&i.PaidInstallments,
		&i.ClosingDay,
		&i.FirstInstallmentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMasterPurchase = `-- name: DeleteMasterPurchase :exec
UPDATE master_purchases
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type DeleteMasterPurchaseParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) DeleteMasterPurchase(ctx context.Context, arg DeleteMasterPurchaseParams) error {
	_, err := q.db.Exec(ctx, deleteMasterPurchase, arg.ID, arg.TenantID)
	return err
}

const getMasterPurchaseByID = `-- name: GetMasterPurchaseByID :one
SELECT id, tenant_id, account_id, category_id, user_id, description, status, total_amount_cents, installment_count, paid_installments, closing_day, first_installment_date, created_at, updated_at, deleted_at FROM master_purchases
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetMasterPurchaseByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetMasterPurchaseByID(ctx context.Context, arg GetMasterPurchaseByIDParams) (MasterPurchase, error) {
	row := q.db.QueryRow(ctx, getMasterPurchaseByID, arg.ID, arg.TenantID)
	var i MasterPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CategoryID,
		&i.UserID,
		&i.Description,
		&i.Status,
		&i.TotalAmountCents,
		&i.InstallmentCount,
		&i.PaidInstallments,
		&i.ClosingDay,
		&i.FirstInstallmentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementPaidInstallments = `-- name: IncrementPaidInstallments :one
UPDATE master_purchases
SET 
    paid_installments = paid_installments + 1,
    status = CASE 
        WHEN paid_installments + 1 >= installment_count THEN 'closed'::master_purchase_status 
        ELSE status 
    END,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, account_id, category_id, user_id, description, status, total_amount_cents, installment_count, paid_installments, closing_day, first_installment_date, created_at, updated_at, deleted_at
`

type IncrementPaidInstallmentsParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) IncrementPaidInstallments(ctx context.Context, arg IncrementPaidInstallmentsParams) (MasterPurchase, error) {
	row := q.db.QueryRow(ctx, incrementPaidInstallments, arg.ID, arg.TenantID)
	var i MasterPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CategoryID,
		&i.UserID,
		&i.Description,
		&i.Status,
		&i.TotalAmountCents,
		&i.InstallmentCount,
		&i.PaidInstallments,
		&i.ClosingDay,
		&i.FirstInstallmentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMasterPurchasesByAccount = `-- name: ListMasterPurchasesByAccount :many
SELECT id, tenant_id, account_id, category_id, user_id, description, status, total_amount_cents, installment_count, paid_installments, closing_day, first_installment_date, created_at, updated_at, deleted_at FROM master_purchases
WHERE tenant_id = $1 AND account_id = $2 AND deleted_at IS NULL
ORDER BY first_installment_date DESC
`

type ListMasterPurchasesByAccountParams struct {
	TenantID  string `json:"tenant_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) ListMasterPurchasesByAccount(ctx context.Context, arg ListMasterPurchasesByAccountParams) ([]MasterPurchase, error) {
	rows, err := q.db.Query(ctx, listMasterPurchasesByAccount, arg.TenantID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterPurchase{}
	for rows.Next() {
		var i MasterPurchase
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.CategoryID,
			&i.UserID,
			&i.Description,
			&i.Status,
			&i.TotalAmountCents,
			&i.InstallmentCount,
			&i.PaidInstallments,
			&i.ClosingDay,
			&i.FirstInstallmentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasterPurchasesByTenant = `-- name: ListMasterPurchasesByTenant :many
SELECT id, tenant_id, account_id, category_id, user_id, description, status, total_amount_cents, installment_count, paid_installments, closing_day, first_installment_date, created_at, updated_at, deleted_at FROM master_purchases
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListMasterPurchasesByTenant(ctx context.Context, tenantID string) ([]MasterPurchase, error) {
	rows, err := q.db.Query(ctx, listMasterPurchasesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterPurchase{}
	for rows.Next() {
		var i MasterPurchase
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.CategoryID,
			&i.UserID,
			&i.Description,
			&i.Status,
			&i.TotalAmountCents,
			&i.InstallmentCount,
			&i.PaidInstallments,
			&i.ClosingDay,
			&i.FirstInstallmentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMasterPurchasesByClosingDay = `-- name: ListPendingMasterPurchasesByClosingDay :many
SELECT id, tenant_id, account_id, category_id, user_id, description, status, total_amount_cents, installment_count, paid_installments, closing_day, first_installment_date, created_at, updated_at, deleted_at FROM master_purchases
WHERE tenant_id = $1 
  AND status = 'open' 
  AND closing_day = $2
  AND deleted_at IS NULL
`

type ListPendingMasterPurchasesByClosingDayParams struct {
	TenantID   string `json:"tenant_id"`
	ClosingDay int16  `json:"closing_day"`
}

func (q *Queries) ListPendingMasterPurchasesByClosingDay(ctx context.Context, arg ListPendingMasterPurchasesByClosingDayParams) ([]MasterPurchase, error) {
	rows, err := q.db.Query(ctx, listPendingMasterPurchasesByClosingDay, arg.TenantID, arg.ClosingDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterPurchase{}
	for rows.Next() {
		var i MasterPurchase
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.CategoryID,
			&i.UserID,
			&i.Description,
			&i.Status,
			&i.TotalAmountCents,
			&i.InstallmentCount,
			&i.PaidInstallments,
			&i.ClosingDay,
			&i.FirstInstallmentDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMasterPurchase = `-- name: UpdateMasterPurchase :one
UPDATE master_purchases
SET 
    category_id = COALESCE(NULLIF($3, ''), category_id),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    paid_installments = COALESCE($6, paid_installments),
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, account_id, category_id, user_id, description, status, total_amount_cents, installment_count, paid_installments, closing_day, first_installment_date, created_at, updated_at, deleted_at
`

type UpdateMasterPurchaseParams struct {
	ID               string                   `json:"id"`
	TenantID         string                   `json:"tenant_id"`
	CategoryID       interface{}              `json:"category_id"`
	Description      pgtype.Text              `json:"description"`
	Status           NullMasterPurchaseStatus `json:"status"`
	PaidInstallments pgtype.Int2              `json:"paid_installments"`
}

func (q *Queries) UpdateMasterPurchase(ctx context.Context, arg UpdateMasterPurchaseParams) (MasterPurchase, error) {
	row := q.db.QueryRow(ctx, updateMasterPurchase,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Description,
		arg.Status,
		arg.PaidInstallments,
	)
	var i MasterPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CategoryID,
		&i.UserID,
		&i.Description,
		&i.Status,
		&i.TotalAmountCents,
		&i.InstallmentCount,
		&i.PaidInstallments,
		&i.ClosingDay,
		&i.FirstInstallmentDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
