// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeChecking   AccountType = "checking"
	AccountTypeSavings    AccountType = "savings"
	AccountTypeCreditCard AccountType = "credit_card"
	AccountTypeInvestment AccountType = "investment"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type AuditAction string

const (
	AuditActionCreate       AuditAction = "create"
	AuditActionUpdate       AuditAction = "update"
	AuditActionSoftDelete   AuditAction = "soft_delete"
	AuditActionRestore      AuditAction = "restore"
	AuditActionLogin        AuditAction = "login"
	AuditActionLoginFailed  AuditAction = "login_failed"
	AuditActionOtpRequested AuditAction = "otp_requested"
	AuditActionOtpVerified  AuditAction = "otp_verified"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type CategoryType string

const (
	CategoryTypeIncome   CategoryType = "income"
	CategoryTypeExpense  CategoryType = "expense"
	CategoryTypeTransfer CategoryType = "transfer"
)

func (e *CategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoryType(s)
	case string:
		*e = CategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoryType: %T", src)
	}
	return nil
}

type NullCategoryType struct {
	CategoryType CategoryType `json:"category_type"`
	Valid        bool         `json:"valid"` // Valid is true if CategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.CategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoryType), nil
}

type TenantPlan string

const (
	TenantPlanFree    TenantPlan = "free"
	TenantPlanBasic   TenantPlan = "basic"
	TenantPlanPremium TenantPlan = "premium"
)

func (e *TenantPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantPlan(s)
	case string:
		*e = TenantPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantPlan: %T", src)
	}
	return nil
}

type NullTenantPlan struct {
	TenantPlan TenantPlan `json:"tenant_plan"`
	Valid      bool       `json:"valid"` // Valid is true if TenantPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantPlan) Scan(value interface{}) error {
	if value == nil {
		ns.TenantPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantPlan), nil
}

type TransactionType string

const (
	TransactionTypeIncome   TransactionType = "income"
	TransactionTypeExpense  TransactionType = "expense"
	TransactionTypeTransfer TransactionType = "transfer"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type UserRole string

const (
	UserRoleSysadmin UserRole = "sysadmin"
	UserRoleAdmin    UserRole = "admin"
	UserRoleMember   UserRole = "member"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Account struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	UserID       string             `json:"user_id"`
	Name         string             `json:"name"`
	Type         AccountType        `json:"type"`
	Currency     string             `json:"currency"`
	BalanceCents int64              `json:"balance_cents"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type AuditLog struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	ActorID    string             `json:"actor_id"`
	ActorRole  UserRole           `json:"actor_role"`
	Action     AuditAction        `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.Text        `json:"entity_id"`
	OldValues  []byte             `json:"old_values"`
	NewValues  []byte             `json:"new_values"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	ParentID  string             `json:"parent_id"`
	Name      string             `json:"name"`
	Icon      pgtype.Text        `json:"icon"`
	Color     pgtype.Text        `json:"color"`
	Type      CategoryType       `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type MasterPurchase struct {
	ID                     string             `json:"id"`
	TenantID               string             `json:"tenant_id"`
	AccountID              string             `json:"account_id"`
	CategoryID             string             `json:"category_id"`
	UserID                 string             `json:"user_id"`
	Description            string             `json:"description"`
	TotalAmountCents       int64              `json:"total_amount_cents"`
	InstallmentCount       int16              `json:"installment_count"`
	InstallmentCents       int64              `json:"installment_cents"`
	FirstDueDate           pgtype.Date        `json:"first_due_date"`
	LastSettledInstallment int16              `json:"last_settled_installment"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
}

type OtpRequest struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	Used      bool               `json:"used"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Plan      TenantPlan         `json:"plan"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Transaction struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	AccountID        string             `json:"account_id"`
	CategoryID       string             `json:"category_id"`
	UserID           string             `json:"user_id"`
	MasterPurchaseID pgtype.Text        `json:"master_purchase_id"`
	Description      string             `json:"description"`
	AmountCents      int64              `json:"amount_cents"`
	Type             TransactionType    `json:"type"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Role        UserRole           `json:"role"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
