// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio_snapshots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPortfolioSnapshot = `-- name: CreatePortfolioSnapshot :one
INSERT INTO portfolio_snapshots (
    id, tenant_id, snapshot_date, total_value_cents, 
    total_income_cents, currency, details
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, snapshot_date, total_value_cents, total_income_cents, currency, details, created_at
`

type CreatePortfolioSnapshotParams struct {
	ID               string      `json:"id"`
	TenantID         string      `json:"tenant_id"`
	SnapshotDate     pgtype.Date `json:"snapshot_date"`
	TotalValueCents  int64       `json:"total_value_cents"`
	TotalIncomeCents int64       `json:"total_income_cents"`
	Currency         string      `json:"currency"`
	Details          []byte      `json:"details"`
}

func (q *Queries) CreatePortfolioSnapshot(ctx context.Context, arg CreatePortfolioSnapshotParams) (PortfolioSnapshot, error) {
	row := q.db.QueryRow(ctx, createPortfolioSnapshot,
		arg.ID,
		arg.TenantID,
		arg.SnapshotDate,
		arg.TotalValueCents,
		arg.TotalIncomeCents,
		arg.Currency,
		arg.Details,
	)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SnapshotDate,
		&i.TotalValueCents,
		&i.TotalIncomeCents,
		&i.Currency,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getPortfolioSnapshotByDate = `-- name: GetPortfolioSnapshotByDate :one
SELECT id, tenant_id, snapshot_date, total_value_cents, total_income_cents, currency, details, created_at FROM portfolio_snapshots
WHERE tenant_id = $1 AND snapshot_date = $2
`

type GetPortfolioSnapshotByDateParams struct {
	TenantID     string      `json:"tenant_id"`
	SnapshotDate pgtype.Date `json:"snapshot_date"`
}

func (q *Queries) GetPortfolioSnapshotByDate(ctx context.Context, arg GetPortfolioSnapshotByDateParams) (PortfolioSnapshot, error) {
	row := q.db.QueryRow(ctx, getPortfolioSnapshotByDate, arg.TenantID, arg.SnapshotDate)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SnapshotDate,
		&i.TotalValueCents,
		&i.TotalIncomeCents,
		&i.Currency,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listPortfolioSnapshots = `-- name: ListPortfolioSnapshots :many
SELECT id, tenant_id, snapshot_date, total_value_cents, total_income_cents, currency, details, created_at FROM portfolio_snapshots
WHERE tenant_id = $1
ORDER BY snapshot_date DESC
`

func (q *Queries) ListPortfolioSnapshots(ctx context.Context, tenantID string) ([]PortfolioSnapshot, error) {
	rows, err := q.db.Query(ctx, listPortfolioSnapshots, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioSnapshot{}
	for rows.Next() {
		var i PortfolioSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SnapshotDate,
			&i.TotalValueCents,
			&i.TotalIncomeCents,
			&i.Currency,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
