// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (
    id, tenant_id, asset_id, account_id, quantity, avg_cost_cents, 
    last_price_cents, currency, purchased_at, income_type, 
    income_interval_days, income_amount_cents, income_rate_bps, 
    next_income_at, maturity_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, tenant_id, asset_id, account_id, quantity, avg_cost_cents, last_price_cents, currency, purchased_at, income_type, income_interval_days, income_amount_cents, income_rate_bps, next_income_at, maturity_at, created_at, updated_at, deleted_at
`

type CreatePositionParams struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	AssetID            string             `json:"asset_id"`
	AccountID          string             `json:"account_id"`
	Quantity           decimal.Decimal    `json:"quantity"`
	AvgCostCents       int64              `json:"avg_cost_cents"`
	LastPriceCents     int64              `json:"last_price_cents"`
	Currency           string             `json:"currency"`
	PurchasedAt        pgtype.Timestamptz `json:"purchased_at"`
	IncomeType         IncomeType         `json:"income_type"`
	IncomeIntervalDays pgtype.Int4        `json:"income_interval_days"`
	IncomeAmountCents  pgtype.Int8        `json:"income_amount_cents"`
	IncomeRateBps      pgtype.Int4        `json:"income_rate_bps"`
	NextIncomeAt       pgtype.Timestamptz `json:"next_income_at"`
	MaturityAt         pgtype.Timestamptz `json:"maturity_at"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.ID,
		arg.TenantID,
		arg.AssetID,
		arg.AccountID,
		arg.Quantity,
		arg.AvgCostCents,
		arg.LastPriceCents,
		arg.Currency,
		arg.PurchasedAt,
		arg.IncomeType,
		arg.IncomeIntervalDays,
		arg.IncomeAmountCents,
		arg.IncomeRateBps,
		arg.NextIncomeAt,
		arg.MaturityAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.AccountID,
		&i.Quantity,
		&i.AvgCostCents,
		&i.LastPriceCents,
		&i.Currency,
		&i.PurchasedAt,
		&i.IncomeType,
		&i.IncomeIntervalDays,
		&i.IncomeAmountCents,
		&i.IncomeRateBps,
		&i.NextIncomeAt,
		&i.MaturityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPositionByID = `-- name: GetPositionByID :one
SELECT id, tenant_id, asset_id, account_id, quantity, avg_cost_cents, last_price_cents, currency, purchased_at, income_type, income_interval_days, income_amount_cents, income_rate_bps, next_income_at, maturity_at, created_at, updated_at, deleted_at FROM positions
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetPositionByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetPositionByID(ctx context.Context, arg GetPositionByIDParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByID, arg.ID, arg.TenantID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.AccountID,
		&i.Quantity,
		&i.AvgCostCents,
		&i.LastPriceCents,
		&i.Currency,
		&i.PurchasedAt,
		&i.IncomeType,
		&i.IncomeIntervalDays,
		&i.IncomeAmountCents,
		&i.IncomeRateBps,
		&i.NextIncomeAt,
		&i.MaturityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPositionsByAccount = `-- name: ListPositionsByAccount :many
SELECT id, tenant_id, asset_id, account_id, quantity, avg_cost_cents, last_price_cents, currency, purchased_at, income_type, income_interval_days, income_amount_cents, income_rate_bps, next_income_at, maturity_at, created_at, updated_at, deleted_at FROM positions
WHERE tenant_id = $1 AND account_id = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListPositionsByAccountParams struct {
	TenantID  string `json:"tenant_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) ListPositionsByAccount(ctx context.Context, arg ListPositionsByAccountParams) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByAccount, arg.TenantID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.AccountID,
			&i.Quantity,
			&i.AvgCostCents,
			&i.LastPriceCents,
			&i.Currency,
			&i.PurchasedAt,
			&i.IncomeType,
			&i.IncomeIntervalDays,
			&i.IncomeAmountCents,
			&i.IncomeRateBps,
			&i.NextIncomeAt,
			&i.MaturityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsByTenant = `-- name: ListPositionsByTenant :many
SELECT id, tenant_id, asset_id, account_id, quantity, avg_cost_cents, last_price_cents, currency, purchased_at, income_type, income_interval_days, income_amount_cents, income_rate_bps, next_income_at, maturity_at, created_at, updated_at, deleted_at FROM positions
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPositionsByTenant(ctx context.Context, tenantID string) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.AccountID,
			&i.Quantity,
			&i.AvgCostCents,
			&i.LastPriceCents,
			&i.Currency,
			&i.PurchasedAt,
			&i.IncomeType,
			&i.IncomeIntervalDays,
			&i.IncomeAmountCents,
			&i.IncomeRateBps,
			&i.NextIncomeAt,
			&i.MaturityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionsDueIncome = `-- name: ListPositionsDueIncome :many
SELECT id, tenant_id, asset_id, account_id, quantity, avg_cost_cents, last_price_cents, currency, purchased_at, income_type, income_interval_days, income_amount_cents, income_rate_bps, next_income_at, maturity_at, created_at, updated_at, deleted_at FROM positions
WHERE income_type != 'none' 
  AND next_income_at <= $1 
  AND deleted_at IS NULL
`

// Scheduler processes all tenants globally.
func (q *Queries) ListPositionsDueIncome(ctx context.Context, nextIncomeAt pgtype.Timestamptz) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositionsDueIncome, nextIncomeAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Position{}
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.AccountID,
			&i.Quantity,
			&i.AvgCostCents,
			&i.LastPriceCents,
			&i.Currency,
			&i.PurchasedAt,
			&i.IncomeType,
			&i.IncomeIntervalDays,
			&i.IncomeAmountCents,
			&i.IncomeRateBps,
			&i.NextIncomeAt,
			&i.MaturityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePosition = `-- name: SoftDeletePosition :exec
UPDATE positions
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type SoftDeletePositionParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) SoftDeletePosition(ctx context.Context, arg SoftDeletePositionParams) error {
	_, err := q.db.Exec(ctx, softDeletePosition, arg.ID, arg.TenantID)
	return err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET quantity = $3,
    avg_cost_cents = $4,
    last_price_cents = $5,
    income_type = $6,
    income_interval_days = $7,
    income_amount_cents = $8,
    income_rate_bps = $9,
    next_income_at = $10,
    maturity_at = $11,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, asset_id, account_id, quantity, avg_cost_cents, last_price_cents, currency, purchased_at, income_type, income_interval_days, income_amount_cents, income_rate_bps, next_income_at, maturity_at, created_at, updated_at, deleted_at
`

type UpdatePositionParams struct {
	ID                 string             `json:"id"`
	TenantID           string             `json:"tenant_id"`
	Quantity           decimal.Decimal    `json:"quantity"`
	AvgCostCents       int64              `json:"avg_cost_cents"`
	LastPriceCents     int64              `json:"last_price_cents"`
	IncomeType         IncomeType         `json:"income_type"`
	IncomeIntervalDays pgtype.Int4        `json:"income_interval_days"`
	IncomeAmountCents  pgtype.Int8        `json:"income_amount_cents"`
	IncomeRateBps      pgtype.Int4        `json:"income_rate_bps"`
	NextIncomeAt       pgtype.Timestamptz `json:"next_income_at"`
	MaturityAt         pgtype.Timestamptz `json:"maturity_at"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.ID,
		arg.TenantID,
		arg.Quantity,
		arg.AvgCostCents,
		arg.LastPriceCents,
		arg.IncomeType,
		arg.IncomeIntervalDays,
		arg.IncomeAmountCents,
		arg.IncomeRateBps,
		arg.NextIncomeAt,
		arg.MaturityAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.AccountID,
		&i.Quantity,
		&i.AvgCostCents,
		&i.LastPriceCents,
		&i.Currency,
		&i.PurchasedAt,
		&i.IncomeType,
		&i.IncomeIntervalDays,
		&i.IncomeAmountCents,
		&i.IncomeRateBps,
		&i.NextIncomeAt,
		&i.MaturityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePositionNextIncome = `-- name: UpdatePositionNextIncome :exec
UPDATE positions
SET next_income_at = $3,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type UpdatePositionNextIncomeParams struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	NextIncomeAt pgtype.Timestamptz `json:"next_income_at"`
}

func (q *Queries) UpdatePositionNextIncome(ctx context.Context, arg UpdatePositionNextIncomeParams) error {
	_, err := q.db.Exec(ctx, updatePositionNextIncome, arg.ID, arg.TenantID, arg.NextIncomeAt)
	return err
}
