// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: position_income_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPositionIncomeEvent = `-- name: CreatePositionIncomeEvent :one
INSERT INTO position_income_events (
    id, tenant_id, position_id, income_type, amount_cents, 
    currency, event_date, status, realized_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, tenant_id, position_id, income_type, amount_cents, currency, event_date, status, realized_at, created_at, updated_at
`

type CreatePositionIncomeEventParams struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	PositionID  string             `json:"position_id"`
	IncomeType  IncomeType         `json:"income_type"`
	AmountCents int64              `json:"amount_cents"`
	Currency    string             `json:"currency"`
	EventDate   pgtype.Date        `json:"event_date"`
	Status      ReceivableStatus   `json:"status"`
	RealizedAt  pgtype.Timestamptz `json:"realized_at"`
}

func (q *Queries) CreatePositionIncomeEvent(ctx context.Context, arg CreatePositionIncomeEventParams) (PositionIncomeEvent, error) {
	row := q.db.QueryRow(ctx, createPositionIncomeEvent,
		arg.ID,
		arg.TenantID,
		arg.PositionID,
		arg.IncomeType,
		arg.AmountCents,
		arg.Currency,
		arg.EventDate,
		arg.Status,
		arg.RealizedAt,
	)
	var i PositionIncomeEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PositionID,
		&i.IncomeType,
		&i.AmountCents,
		&i.Currency,
		&i.EventDate,
		&i.Status,
		&i.RealizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPositionIncomeEventByID = `-- name: GetPositionIncomeEventByID :one
SELECT id, tenant_id, position_id, income_type, amount_cents, currency, event_date, status, realized_at, created_at, updated_at FROM position_income_events
WHERE id = $1 AND tenant_id = $2
`

type GetPositionIncomeEventByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetPositionIncomeEventByID(ctx context.Context, arg GetPositionIncomeEventByIDParams) (PositionIncomeEvent, error) {
	row := q.db.QueryRow(ctx, getPositionIncomeEventByID, arg.ID, arg.TenantID)
	var i PositionIncomeEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PositionID,
		&i.IncomeType,
		&i.AmountCents,
		&i.Currency,
		&i.EventDate,
		&i.Status,
		&i.RealizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingIncomeEvents = `-- name: ListPendingIncomeEvents :many
SELECT id, tenant_id, position_id, income_type, amount_cents, currency, event_date, status, realized_at, created_at, updated_at FROM position_income_events
WHERE tenant_id = $1 AND status = 'pending'
ORDER BY event_date ASC
`

func (q *Queries) ListPendingIncomeEvents(ctx context.Context, tenantID string) ([]PositionIncomeEvent, error) {
	rows, err := q.db.Query(ctx, listPendingIncomeEvents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PositionIncomeEvent{}
	for rows.Next() {
		var i PositionIncomeEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PositionID,
			&i.IncomeType,
			&i.AmountCents,
			&i.Currency,
			&i.EventDate,
			&i.Status,
			&i.RealizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionIncomeEventsByTenant = `-- name: ListPositionIncomeEventsByTenant :many
SELECT id, tenant_id, position_id, income_type, amount_cents, currency, event_date, status, realized_at, created_at, updated_at FROM position_income_events
WHERE tenant_id = $1
ORDER BY event_date DESC
`

func (q *Queries) ListPositionIncomeEventsByTenant(ctx context.Context, tenantID string) ([]PositionIncomeEvent, error) {
	rows, err := q.db.Query(ctx, listPositionIncomeEventsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PositionIncomeEvent{}
	for rows.Next() {
		var i PositionIncomeEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PositionID,
			&i.IncomeType,
			&i.AmountCents,
			&i.Currency,
			&i.EventDate,
			&i.Status,
			&i.RealizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncomeEventStatus = `-- name: UpdateIncomeEventStatus :one
UPDATE position_income_events
SET status = $3,
    realized_at = $4,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, position_id, income_type, amount_cents, currency, event_date, status, realized_at, created_at, updated_at
`

type UpdateIncomeEventStatusParams struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	Status     ReceivableStatus   `json:"status"`
	RealizedAt pgtype.Timestamptz `json:"realized_at"`
}

func (q *Queries) UpdateIncomeEventStatus(ctx context.Context, arg UpdateIncomeEventStatusParams) (PositionIncomeEvent, error) {
	row := q.db.QueryRow(ctx, updateIncomeEventStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.RealizedAt,
	)
	var i PositionIncomeEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PositionID,
		&i.IncomeType,
		&i.AmountCents,
		&i.Currency,
		&i.EventDate,
		&i.Status,
		&i.RealizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
