// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: position_snapshots.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createPositionSnapshot = `-- name: CreatePositionSnapshot :one
INSERT INTO position_snapshots (
    id, tenant_id, position_id, snapshot_date, quantity, 
    avg_cost_cents, last_price_cents, currency
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, position_id, snapshot_date, quantity, avg_cost_cents, last_price_cents, currency, created_at
`

type CreatePositionSnapshotParams struct {
	ID             string          `json:"id"`
	TenantID       string          `json:"tenant_id"`
	PositionID     string          `json:"position_id"`
	SnapshotDate   pgtype.Date     `json:"snapshot_date"`
	Quantity       decimal.Decimal `json:"quantity"`
	AvgCostCents   int64           `json:"avg_cost_cents"`
	LastPriceCents int64           `json:"last_price_cents"`
	Currency       string          `json:"currency"`
}

func (q *Queries) CreatePositionSnapshot(ctx context.Context, arg CreatePositionSnapshotParams) (PositionSnapshot, error) {
	row := q.db.QueryRow(ctx, createPositionSnapshot,
		arg.ID,
		arg.TenantID,
		arg.PositionID,
		arg.SnapshotDate,
		arg.Quantity,
		arg.AvgCostCents,
		arg.LastPriceCents,
		arg.Currency,
	)
	var i PositionSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PositionID,
		&i.SnapshotDate,
		&i.Quantity,
		&i.AvgCostCents,
		&i.LastPriceCents,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getPositionSnapshotByID = `-- name: GetPositionSnapshotByID :one
SELECT id, tenant_id, position_id, snapshot_date, quantity, avg_cost_cents, last_price_cents, currency, created_at FROM position_snapshots
WHERE id = $1 AND tenant_id = $2
`

type GetPositionSnapshotByIDParams struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetPositionSnapshotByID(ctx context.Context, arg GetPositionSnapshotByIDParams) (PositionSnapshot, error) {
	row := q.db.QueryRow(ctx, getPositionSnapshotByID, arg.ID, arg.TenantID)
	var i PositionSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PositionID,
		&i.SnapshotDate,
		&i.Quantity,
		&i.AvgCostCents,
		&i.LastPriceCents,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const listPositionSnapshotsByPosition = `-- name: ListPositionSnapshotsByPosition :many
SELECT id, tenant_id, position_id, snapshot_date, quantity, avg_cost_cents, last_price_cents, currency, created_at FROM position_snapshots
WHERE position_id = $1 AND tenant_id = $2
ORDER BY snapshot_date DESC
`

type ListPositionSnapshotsByPositionParams struct {
	PositionID string `json:"position_id"`
	TenantID   string `json:"tenant_id"`
}

func (q *Queries) ListPositionSnapshotsByPosition(ctx context.Context, arg ListPositionSnapshotsByPositionParams) ([]PositionSnapshot, error) {
	rows, err := q.db.Query(ctx, listPositionSnapshotsByPosition, arg.PositionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PositionSnapshot{}
	for rows.Next() {
		var i PositionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PositionID,
			&i.SnapshotDate,
			&i.Quantity,
			&i.AvgCostCents,
			&i.LastPriceCents,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionSnapshotsByTenantSince = `-- name: ListPositionSnapshotsByTenantSince :many
SELECT id, tenant_id, position_id, snapshot_date, quantity, avg_cost_cents, last_price_cents, currency, created_at FROM position_snapshots
WHERE tenant_id = $1 AND snapshot_date >= $2
ORDER BY snapshot_date DESC, created_at DESC
`

type ListPositionSnapshotsByTenantSinceParams struct {
	TenantID     string      `json:"tenant_id"`
	SnapshotDate pgtype.Date `json:"snapshot_date"`
}

func (q *Queries) ListPositionSnapshotsByTenantSince(ctx context.Context, arg ListPositionSnapshotsByTenantSinceParams) ([]PositionSnapshot, error) {
	rows, err := q.db.Query(ctx, listPositionSnapshotsByTenantSince, arg.TenantID, arg.SnapshotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PositionSnapshot{}
	for rows.Next() {
		var i PositionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PositionID,
			&i.SnapshotDate,
			&i.Quantity,
			&i.AvgCostCents,
			&i.LastPriceCents,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
