// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AdminForceDeleteUser(ctx context.Context, id string) error
	AdminGetTenantByID(ctx context.Context, id string) (Tenant, error)
	AdminGetUserByID(ctx context.Context, id string) (User, error)
	AdminHardDeleteTenant(ctx context.Context, id string) error
	AdminListAllAuditLogs(ctx context.Context, arg AdminListAllAuditLogsParams) ([]AuditLog, error)
	AdminListAllTenants(ctx context.Context, withDeleted bool) ([]Tenant, error)
	AdminListAllUsers(ctx context.Context) ([]User, error)
	AdminRestoreTenant(ctx context.Context, id string) error
	AdminSuspendTenant(ctx context.Context, id string) error
	AdminUpdateTenantPlan(ctx context.Context, arg AdminUpdateTenantPlanParams) (Tenant, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOTPRequest(ctx context.Context, arg CreateOTPRequestParams) (OtpRequest, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredOTPs(ctx context.Context) error
	GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error)
	GetActiveOTPByEmail(ctx context.Context, email string) (OtpRequest, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetTenantByID(ctx context.Context, id string) (Tenant, error)
	GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	ListAccountsByTenant(ctx context.Context, tenantID string) ([]Account, error)
	ListAccountsByUser(ctx context.Context, arg ListAccountsByUserParams) ([]Account, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListAuditLogsByTenant(ctx context.Context, arg ListAuditLogsByTenantParams) ([]AuditLog, error)
	ListCategoriesByTenant(ctx context.Context, tenantID string) ([]Category, error)
	ListChildCategories(ctx context.Context, arg ListChildCategoriesParams) ([]Category, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListTransactionsByTenant(ctx context.Context, arg ListTransactionsByTenantParams) ([]Transaction, error)
	ListUsersByTenant(ctx context.Context, tenantID string) ([]User, error)
	MarkOTPUsed(ctx context.Context, id string) error
	SoftDeleteAccount(ctx context.Context, arg SoftDeleteAccountParams) error
	SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error
	SoftDeleteTenant(ctx context.Context, id string) error
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
