// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_asset_configs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAssetWithTenantConfig = `-- name: GetAssetWithTenantConfig :one
SELECT
    a.id,
    a.ticker,
    a.isin,
    a.asset_type,
    a.created_at,
    COALESCE(tac.name,     a.name)     AS name,
    COALESCE(tac.currency, a.currency) AS currency,
    COALESCE(tac.details,  a.details)  AS details,
    tac.id         AS config_id,
    tac.created_at AS tenant_added_at
FROM assets a
LEFT JOIN tenant_asset_configs tac
       ON tac.asset_id = a.id
      AND tac.tenant_id = $1
      AND tac.deleted_at IS NULL
WHERE a.id = $2
`

type GetAssetWithTenantConfigParams struct {
	TenantID string `json:"tenant_id"`
	AssetID  string `json:"asset_id"`
}

type GetAssetWithTenantConfigRow struct {
	ID            string             `json:"id"`
	Ticker        string             `json:"ticker"`
	Isin          pgtype.Text        `json:"isin"`
	AssetType     AssetType          `json:"asset_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Name          string             `json:"name"`
	Currency      string             `json:"currency"`
	Details       pgtype.Text        `json:"details"`
	ConfigID      string             `json:"config_id"`
	TenantAddedAt pgtype.Timestamptz `json:"tenant_added_at"`
}

// Returns the global asset with tenant overrides applied via COALESCE.
// Use this query in all asset-display contexts (ADR §2.7).
func (q *Queries) GetAssetWithTenantConfig(ctx context.Context, arg GetAssetWithTenantConfigParams) (GetAssetWithTenantConfigRow, error) {
	row := q.db.QueryRow(ctx, getAssetWithTenantConfig, arg.TenantID, arg.AssetID)
	var i GetAssetWithTenantConfigRow
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Isin,
		&i.AssetType,
		&i.CreatedAt,
		&i.Name,
		&i.Currency,
		&i.Details,
		&i.ConfigID,
		&i.TenantAddedAt,
	)
	return i, err
}

const getTenantAssetConfigByAssetID = `-- name: GetTenantAssetConfigByAssetID :one
SELECT id, tenant_id, asset_id, name, currency, details, created_at, updated_at, deleted_at FROM tenant_asset_configs
WHERE tenant_id = $1
  AND asset_id  = $2
  AND deleted_at IS NULL
`

type GetTenantAssetConfigByAssetIDParams struct {
	TenantID string `json:"tenant_id"`
	AssetID  string `json:"asset_id"`
}

func (q *Queries) GetTenantAssetConfigByAssetID(ctx context.Context, arg GetTenantAssetConfigByAssetIDParams) (TenantAssetConfig, error) {
	row := q.db.QueryRow(ctx, getTenantAssetConfigByAssetID, arg.TenantID, arg.AssetID)
	var i TenantAssetConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.Name,
		&i.Currency,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenantAssetConfigs = `-- name: ListTenantAssetConfigs :many
SELECT id, tenant_id, asset_id, name, currency, details, created_at, updated_at, deleted_at FROM tenant_asset_configs
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListTenantAssetConfigs(ctx context.Context, tenantID string) ([]TenantAssetConfig, error) {
	rows, err := q.db.Query(ctx, listTenantAssetConfigs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantAssetConfig{}
	for rows.Next() {
		var i TenantAssetConfig
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetID,
			&i.Name,
			&i.Currency,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenantAssetConfig = `-- name: SoftDeleteTenantAssetConfig :exec
UPDATE tenant_asset_configs
SET deleted_at = NOW()
WHERE tenant_id = $1
  AND asset_id  = $2
  AND deleted_at IS NULL
`

type SoftDeleteTenantAssetConfigParams struct {
	TenantID string `json:"tenant_id"`
	AssetID  string `json:"asset_id"`
}

func (q *Queries) SoftDeleteTenantAssetConfig(ctx context.Context, arg SoftDeleteTenantAssetConfigParams) error {
	_, err := q.db.Exec(ctx, softDeleteTenantAssetConfig, arg.TenantID, arg.AssetID)
	return err
}

const upsertTenantAssetConfig = `-- name: UpsertTenantAssetConfig :one
INSERT INTO tenant_asset_configs (id, tenant_id, asset_id, name, currency, details, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (tenant_id, asset_id) WHERE deleted_at IS NULL
DO UPDATE SET
    name       = EXCLUDED.name,
    currency   = EXCLUDED.currency,
    details    = EXCLUDED.details,
    updated_at = NOW()
RETURNING id, tenant_id, asset_id, name, currency, details, created_at, updated_at, deleted_at
`

type UpsertTenantAssetConfigParams struct {
	ID       string      `json:"id"`
	TenantID string      `json:"tenant_id"`
	AssetID  string      `json:"asset_id"`
	Name     pgtype.Text `json:"name"`
	Currency pgtype.Text `json:"currency"`
	Details  pgtype.Text `json:"details"`
}

func (q *Queries) UpsertTenantAssetConfig(ctx context.Context, arg UpsertTenantAssetConfigParams) (TenantAssetConfig, error) {
	row := q.db.QueryRow(ctx, upsertTenantAssetConfig,
		arg.ID,
		arg.TenantID,
		arg.AssetID,
		arg.Name,
		arg.Currency,
		arg.Details,
	)
	var i TenantAssetConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetID,
		&i.Name,
		&i.Currency,
		&i.Details,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
