// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    id, name, plan, created_at, updated_at
) VALUES (
    $1, $2, $3, NOW(), NOW()
) RETURNING id, name, plan, created_at, updated_at, deleted_at
`

type CreateTenantParams struct {
	ID   string     `json:"id"`
	Name string     `json:"name"`
	Plan TenantPlan `json:"plan"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.ID, arg.Name, arg.Plan)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, plan, created_at, updated_at, deleted_at
FROM tenants
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTenant = `-- name: SoftDeleteTenant :exec
UPDATE tenants
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteTenant, id)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2,
    plan = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, plan, created_at, updated_at, deleted_at
`

type UpdateTenantParams struct {
	ID   string     `json:"id"`
	Name string     `json:"name"`
	Plan TenantPlan `json:"plan"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.ID, arg.Name, arg.Plan)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
