// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    id, tenant_id, account_id, category_id, user_id, 
    master_purchase_id, description, amount_cents, type, 
    occurred_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW()
) RETURNING id, tenant_id, account_id, category_id, user_id, master_purchase_id, description, amount_cents, type, occurred_at, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	ID               string             `json:"id"`
	TenantID         string             `json:"tenant_id"`
	AccountID        string             `json:"account_id"`
	CategoryID       string             `json:"category_id"`
	UserID           string             `json:"user_id"`
	MasterPurchaseID pgtype.Text        `json:"master_purchase_id"`
	Description      string             `json:"description"`
	AmountCents      int64              `json:"amount_cents"`
	Type             TransactionType    `json:"type"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.TenantID,
		arg.AccountID,
		arg.CategoryID,
		arg.UserID,
		arg.MasterPurchaseID,
		arg.Description,
		arg.AmountCents,
		arg.Type,
		arg.OccurredAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CategoryID,
		&i.UserID,
		&i.MasterPurchaseID,
		&i.Description,
		&i.AmountCents,
		&i.Type,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, tenant_id, account_id, category_id, user_id, master_purchase_id, description, amount_cents, type, occurred_at, created_at, updated_at, deleted_at
FROM transactions
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetTransactionByIDParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, arg.TenantID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CategoryID,
		&i.UserID,
		&i.MasterPurchaseID,
		&i.Description,
		&i.AmountCents,
		&i.Type,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTransactionsByTenant = `-- name: ListTransactionsByTenant :many
SELECT id, tenant_id, account_id, category_id, user_id, master_purchase_id, description, amount_cents, type, occurred_at, created_at, updated_at, deleted_at
FROM transactions
WHERE tenant_id = $1 
    AND ($2::CHAR(26) IS NULL OR account_id = $2)
    AND ($3::CHAR(26) IS NULL OR category_id = $3)
    AND ($4::TIMESTAMPTZ IS NULL OR occurred_at >= $4)
    AND ($5::TIMESTAMPTZ IS NULL OR occurred_at <= $5)
    AND deleted_at IS NULL
ORDER BY occurred_at DESC
LIMIT $7 OFFSET $6
`

type ListTransactionsByTenantParams struct {
	TenantID   string             `json:"tenant_id"`
	AccountID  pgtype.Text        `json:"account_id"`
	CategoryID pgtype.Text        `json:"category_id"`
	StartDate  pgtype.Timestamptz `json:"start_date"`
	EndDate    pgtype.Timestamptz `json:"end_date"`
	OffsetOff  int32              `json:"offset_off"`
	LimitOff   int32              `json:"limit_off"`
}

// One query with optional filters using COALESCE or IS NULL pattern
func (q *Queries) ListTransactionsByTenant(ctx context.Context, arg ListTransactionsByTenantParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByTenant,
		arg.TenantID,
		arg.AccountID,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
		arg.OffsetOff,
		arg.LimitOff,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AccountID,
			&i.CategoryID,
			&i.UserID,
			&i.MasterPurchaseID,
			&i.Description,
			&i.AmountCents,
			&i.Type,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions
SET deleted_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteTransactionParams struct {
	TenantID string `json:"tenant_id"`
	ID       string `json:"id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, softDeleteTransaction, arg.TenantID, arg.ID)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET account_id = $3,
    category_id = $4,
    description = $5,
    amount_cents = $6,
    type = $7,
    occurred_at = $8,
    master_purchase_id = $9,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, account_id, category_id, user_id, master_purchase_id, description, amount_cents, type, occurred_at, created_at, updated_at, deleted_at
`

type UpdateTransactionParams struct {
	TenantID         string             `json:"tenant_id"`
	ID               string             `json:"id"`
	AccountID        string             `json:"account_id"`
	CategoryID       string             `json:"category_id"`
	Description      string             `json:"description"`
	AmountCents      int64              `json:"amount_cents"`
	Type             TransactionType    `json:"type"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	MasterPurchaseID pgtype.Text        `json:"master_purchase_id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.TenantID,
		arg.ID,
		arg.AccountID,
		arg.CategoryID,
		arg.Description,
		arg.AmountCents,
		arg.Type,
		arg.OccurredAt,
		arg.MasterPurchaseID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AccountID,
		&i.CategoryID,
		&i.UserID,
		&i.MasterPurchaseID,
		&i.Description,
		&i.AmountCents,
		&i.Type,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
