// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package postgres

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id, entity_id, currency_id, name, type, balance_cents, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, entity_id, currency_id, name, type, balance_cents, metadata, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	Metadata     []byte `json:"metadata"`
	ID           string `json:"id"`
	EntityID     string `json:"entity_id"`
	CurrencyID   string `json:"currency_id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	BalanceCents int64  `json:"balance_cents"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.EntityID,
		arg.CurrencyID,
		arg.Name,
		arg.Type,
		arg.BalanceCents,
		arg.Metadata,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.CurrencyID,
		&i.Name,
		&i.Type,
		&i.BalanceCents,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, entity_id, currency_id, name, type, balance_cents, metadata, created_at, updated_at, deleted_at FROM accounts
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.CurrencyID,
		&i.Name,
		&i.Type,
		&i.BalanceCents,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByEntity = `-- name: ListAccountsByEntity :many
SELECT id, entity_id, currency_id, name, type, balance_cents, metadata, created_at, updated_at, deleted_at FROM accounts
WHERE entity_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListAccountsByEntity(ctx context.Context, entityID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.CurrencyID,
			&i.Name,
			&i.Type,
			&i.BalanceCents,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET 
    balance_cents = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, entity_id, currency_id, name, type, balance_cents, metadata, created_at, updated_at, deleted_at
`

type UpdateAccountBalanceParams struct {
	ID           string `json:"id"`
	BalanceCents int64  `json:"balance_cents"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.BalanceCents)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.CurrencyID,
		&i.Name,
		&i.Type,
		&i.BalanceCents,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
