// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currencies.sql

package postgres

import (
	"context"
)

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currencies (
    id, code, symbol, fallback_decimals, config
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, code, symbol, fallback_decimals, config, created_at, updated_at
`

type CreateCurrencyParams struct {
	ID               string `json:"id"`
	Code             string `json:"code"`
	Symbol           string `json:"symbol"`
	Config           []byte `json:"config"`
	FallbackDecimals int32  `json:"fallback_decimals"`
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRow(ctx, createCurrency,
		arg.ID,
		arg.Code,
		arg.Symbol,
		arg.FallbackDecimals,
		arg.Config,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Symbol,
		&i.FallbackDecimals,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrency = `-- name: GetCurrency :one
SELECT id, code, symbol, fallback_decimals, config, created_at, updated_at FROM currencies
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCurrency(ctx context.Context, id string) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrency, id)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Symbol,
		&i.FallbackDecimals,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, code, symbol, fallback_decimals, config, created_at, updated_at FROM currencies
ORDER BY code
`

func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Symbol,
			&i.FallbackDecimals,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrency = `-- name: UpdateCurrency :one
UPDATE currencies
SET 
    code = $2,
    symbol = $3,
    fallback_decimals = $4,
    config = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, code, symbol, fallback_decimals, config, created_at, updated_at
`

type UpdateCurrencyParams struct {
	ID               string `json:"id"`
	Code             string `json:"code"`
	Symbol           string `json:"symbol"`
	Config           []byte `json:"config"`
	FallbackDecimals int32  `json:"fallback_decimals"`
}

func (q *Queries) UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error) {
	row := q.db.QueryRow(ctx, updateCurrency,
		arg.ID,
		arg.Code,
		arg.Symbol,
		arg.FallbackDecimals,
		arg.Config,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Symbol,
		&i.FallbackDecimals,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
