// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package postgres

import (
	"context"
)

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (
    id, name, role, metadata
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, role, metadata, created_at, updated_at, deleted_at
`

type CreateEntityParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Role     string `json:"role"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntity,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Metadata,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEntity = `-- name: DeleteEntity :exec
UPDATE entities
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteEntity(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEntity, id)
	return err
}

const getEntity = `-- name: GetEntity :one
SELECT id, name, role, metadata, created_at, updated_at, deleted_at FROM entities
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetEntity(ctx context.Context, id string) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntity, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEntities = `-- name: ListEntities :many
SELECT id, name, role, metadata, created_at, updated_at, deleted_at FROM entities
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListEntities(ctx context.Context) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntity = `-- name: UpdateEntity :one
UPDATE entities
SET 
    name = $2,
    role = $3,
    metadata = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, role, metadata, created_at, updated_at, deleted_at
`

type UpdateEntityParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Role     string `json:"role"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, updateEntity,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.Metadata,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
