// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	Metadata     []byte             `json:"metadata"`
	ID           string             `json:"id"`
	EntityID     string             `json:"entity_id"`
	CurrencyID   string             `json:"currency_id"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	BalanceCents int64              `json:"balance_cents"`
}

type Currency struct {
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Config           []byte             `json:"config"`
	ID               string             `json:"id"`
	Code             string             `json:"code"`
	Symbol           string             `json:"symbol"`
	FallbackDecimals int32              `json:"fallback_decimals"`
}

type Entity struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Metadata  []byte             `json:"metadata"`
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
}
