// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	DeleteAccount(ctx context.Context, id string) error
	DeleteEntity(ctx context.Context, id string) error
	GetAccount(ctx context.Context, id string) (Account, error)
	GetCurrency(ctx context.Context, id string) (Currency, error)
	GetEntity(ctx context.Context, id string) (Entity, error)
	ListAccountsByEntity(ctx context.Context, entityID string) ([]Account, error)
	ListCurrencies(ctx context.Context) ([]Currency, error)
	ListEntities(ctx context.Context) ([]Entity, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateCurrency(ctx context.Context, arg UpdateCurrencyParams) (Currency, error)
	UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error)
}

var _ Querier = (*Queries)(nil)
