// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/garnizeh/moolah/internal/domain"
)

type BaseProps struct {
	Title       string
	CurrentPath string
	User        *domain.User
	Tenant      *domain.Tenant
	Content     templ.Component
}

func base(props BaseProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" x-data x-bind:class=\"{ dark: $store.theme.dark }\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/base.templ`, Line: 21, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " — Moolah</title><link rel=\"stylesheet\" href=\"/static/css/app.min.css\"><script defer src=\"/static/js/alpine.min.js\"></script><script defer src=\"/static/js/htmx.min.js\"></script><script>\n\t\t\t\tdocument.addEventListener('alpine:init', () => {\n\t\t\t\t\tAlpine.store('nav', {\n\t\t\t\t\t\topen: false,\n\t\t\t\t\t\ttoggle() { this.open = !this.open; },\n\t\t\t\t\t\tclose() { this.open = false; }\n\t\t\t\t\t});\n\n\t\t\t\t\tAlpine.store('theme', {\n\t\t\t\t\t\tdark: localStorage.getItem('theme') === 'dark' ||\n\t\t\t\t\t\t\t(!localStorage.getItem('theme') && window.matchMedia('(prefers-color-scheme: dark)').matches),\n\t\t\t\t\t\ttoggle() {\n\t\t\t\t\t\t\tthis.dark = !this.dark;\n\t\t\t\t\t\t\tlocalStorage.setItem('theme', this.dark ? 'dark' : 'light');\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\n\t\t\t\t\tAlpine.store('toasts', {\n\t\t\t\t\t\titems: [],\n\t\t\t\t\t\tadd(msg, type = 'info', duration = 4000) {\n\t\t\t\t\t\t\tconst id = Date.now();\n\t\t\t\t\t\t\tthis.items.push({ id, msg, type });\n\t\t\t\t\t\t\tsetTimeout(() => this.remove(id), duration);\n\t\t\t\t\t\t},\n\t\t\t\t\t\tremove(id) { this.items = this.items.filter(t => t.id !== id); }\n\t\t\t\t\t});\n\t\t\t\t});\n\t\t\t</script></head><body class=\"bg-[--color-bg] text-[--color-text-primary] transition-colors duration-[--duration-base]\"><!-- Mobile sidebar overlay backdrop --><div x-show=\"$store.nav.open\" x-transition:enter=\"transition ease-out duration-300\" x-transition:enter-start=\"opacity-0\" x-transition:enter-end=\"opacity-100\" x-transition:leave=\"transition ease-in duration-200\" x-transition:leave-start=\"opacity-100\" x-transition:leave-end=\"opacity-0\" @click=\"$store.nav.close()\" class=\"fixed inset-0 z-20 bg-black/50 lg:hidden\"></div><!-- Sidebar -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = sidebar(props).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- Main column --><div class=\"lg:pl-64 flex flex-col min-h-screen\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = topbar(props).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<!-- HTMX progress bar --><div id=\"htmx-progress\" class=\"htmx-indicator fixed top-0 left-0 right-0 h-1 bg-brand-500 z-50\"></div><!-- Page content slot --><main id=\"main-content\" class=\"flex-1 p-4 lg:p-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = props.Content.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</main></div><!-- Global toast container -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = toastContainer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func toastContainer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"fixed bottom-4 right-4 z-50 flex flex-col gap-2 pointer-events-none\" x-data><template x-for=\"toast in $store.toasts.items\" :key=\"toast.id\"><div class=\"p-4 rounded-lg shadow-lg text-white font-medium pointer-events-auto min-w-[300px]\" :class=\"{\n\t\t\t\t\t'bg-success-600': toast.type === 'success',\n\t\t\t\t\t'bg-danger-600': toast.type === 'error',\n\t\t\t\t\t'bg-brand-600': toast.type === 'info',\n\t\t\t\t\t'bg-warning-600': toast.type === 'warning'\n\t\t\t\t}\" x-transition:enter=\"transition ease-out duration-300\" x-transition:enter-start=\"translate-y-2 opacity-0\" x-transition:enter-end=\"translate-y-0 opacity-100\" x-transition:leave=\"transition ease-in duration-200\" x-transition:leave-start=\"translate-y-0 opacity-100\" x-transition:leave-end=\"translate-y-2 opacity-0\"><div class=\"flex items-center justify-between\"><span x-text=\"toast.msg\"></span> <button @click=\"$store.toasts.remove(toast.id)\" class=\"ml-4 opacity-70 hover:opacity-100\">&times;</button></div></div></template></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
