// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type BadgeVariant string

const (
	BadgeSuccess BadgeVariant = "success"
	BadgeDanger  BadgeVariant = "danger"
	BadgeWarning BadgeVariant = "warning"
	BadgeInfo    BadgeVariant = "info"
	BadgeNeutral BadgeVariant = "neutral"
)

type BadgeSize string

const (
	BadgeSm BadgeSize = "sm"
	BadgeMd BadgeSize = "md"
)

type BadgeProps struct {
	Label   string
	Variant BadgeVariant
	Size    BadgeSize
	Class   string
}

func getBadgeStyles(variant BadgeVariant, size BadgeSize) string {
	var styles string

	// Base styles
	styles = "inline-flex items-center rounded-full font-medium"

	// Size styles
	switch size {
	case BadgeSm:
		styles += " px-2 py-0.5 text-xs"
	default:
		styles += " px-2.5 py-0.5 text-sm"
	}

	// Variant styles
	switch variant {
	case BadgeSuccess:
		styles += " bg-success-50 text-success-700 ring-1 ring-inset ring-success-600/20 dark:bg-success-900/10 dark:text-success-500 dark:ring-success-500/20"
	case BadgeDanger:
		styles += " bg-danger-50 text-danger-700 ring-1 ring-inset ring-danger-600/20 dark:bg-danger-900/10 dark:text-danger-500 dark:ring-danger-500/20"
	case BadgeWarning:
		styles += " bg-warning-50 text-warning-700 ring-1 ring-inset ring-warning-600/20 dark:bg-warning-900/10 dark:text-warning-500 dark:ring-warning-500/20"
	case BadgeInfo:
		styles += " bg-info-50 text-info-700 ring-1 ring-inset ring-info-600/20 dark:bg-info-900/10 dark:text-info-500 dark:ring-info-500/20"
	default:
		styles += " bg-neutral-50 text-neutral-600 ring-1 ring-inset ring-neutral-500/10 dark:bg-neutral-400/10 dark:text-neutral-400 dark:ring-neutral-400/20"
	}

	return styles
}

func Badge(props BadgeProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{getBadgeStyles(props.Variant, props.Size), props.Class}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/badge.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(props.Label)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/badge.templ`, Line: 60, Col: 15}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
